# Generated by Django 5.2.9 on 2026-01-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
