# Generated by Django 5.2.9 on 2026-01-27 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despacho', '0001_initial'),
        ('produccion', '0001_initial'),
        ('sucursales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='despacho.despacho'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.producto'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.producto'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursales'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saldos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.producto'),
        ),
        migrations.AddField(
            model_name='saldos',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursales'),
        ),
        migrations.AddField(
            model_name='saldos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
