# Generated by Django 5.2.9 on 2026-01-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldos',
            name='producto',
            field=models.CharField(max_length=100),
        ),
    ]
