# Generated by Django 5.2.9 on 2026-01-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0003_alter_saldos_producto'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.producto'),
        ),
    ]
