# Generated by Django 5.2.9 on 2026-01-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0005_alter_saldos_options_alter_saldos_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldos',
            old_name='cantidad',
            new_name='saldo_ayer',
        ),
        migrations.AddField(
            model_name='saldos',
            name='saldo_hoy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
