# Generated by Django 5.2.9 on 2026-01-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Tortas', 'Tortas'), ('Pasteles', 'Pasteles'), ('Contratos', 'Contratos')], default='Tortas', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(choices=[('Blanca 20p', 'Blanca 20p'), ('Blanca 10p', 'Blanca 10p'), ('Jaleada 20p', 'Jaleada 20p'), ('Jaleada 10p', 'Jaleada 10p'), ('Moca 20p', 'Moca 20p'), ('Moca 10p', 'Moca 10p'), ('Selva Negra20p', 'Selva Negra20p'), ('Selva Negra 10p', 'Selva Negra 10p'), ('Tres Leches 20p', 'Tres Leches 20p'), ('Tres Leches 10p', 'Tres Leches 10p'), ('Maracuya 20p', 'Maracuya 20p'), ('Maracuya 10p', 'Maracuya 10p'), ('Chocomoca 20p', 'Chocomoca 20p'), ('Chocomoca 10p', 'Chocomoca 10p'), ('Chocodelis 20p', 'Chocodelis 20p'), ('Chocodelis 10p', 'Chocodelis 10p'), ('Porcion de Frutas', 'Porcion de Frutas'), ('Porcion Moca', 'Porcion Moca'), ('Porcion Selva Negra', 'Porcion Selva Negra'), ('Porcion 3 Leches', 'Porcion 3 Leches'), ('Porcion Maracuya', 'Porcion Maracuya'), ('Porcion chocomooka', 'Porcion chocomooka'), ('Porcion Chocodelis', 'Porcion Chocodelis'), ('Alfafor', 'Alfafor'), ('Copas', 'Copas'), ('Chesecake vaso', 'Chesecake vaso'), ('Mouse Copa', 'Mouse Copa'), ('Mouse entero', 'Mouse entero'), ('Mil hojas', 'Mil hojas'), ('Brownie Chocolate', 'Brownie Chocolate'), ('Brownie  Quinua', 'Brownie  Quinua'), ('Brownie Maracuya', 'Brownie Maracuya'), ('Bomba', 'Bomba'), ('Brazo Gitano', 'Brazo Gitano'), ('Pie de manzana porc.', 'Pie de manzana porc.'), ('Pie de limon  porc.', 'Pie de limon  porc.'), ('Pie de piña porc.', 'Pie de piña porc.'), ('Pie de frutas porc.', 'Pie de frutas porc.'), ('Pie de manzana ent.', 'Pie de manzana ent.'), ('Pie de limon ent.', 'Pie de limon ent.'), ('Pie de piña  ent.', 'Pie de piña  ent.'), ('Pie de frutas ent.', 'Pie de frutas ent.'), ('Conitos', 'Conitos'), ('Cupcakes', 'Cupcakes'), ('Queque ', 'Queque '), ('Muffy', 'Muffy'), ('Mini bomba', 'Mini bomba'), ('Rollo', 'Rollo'), ('Empanadas', 'Empanadas'), ('Croisant', 'Croisant'), ('Pan Pizza', 'Pan Pizza'), ('Blanca de 30p', 'Blanca de 30p')], default='Blanca 20p', max_length=200)),
                ('codigo_producto', models.IntegerField(default=1)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_producto', models.IntegerField(default=1)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.categoria')),
                ('sucursal_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursales')),
            ],
            options={
                'verbose_name': 'Producto venta',
                'verbose_name_plural': 'Productos ventas',
                'ordering': ['nombre'],
            },
        ),
    ]
