# Generated by Django 5.2.9 on 2026-01-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(choices=[('01Blanca 20p', 'Blanca 20p'), ('02Blanca 10p', 'Blanca 10p'), ('03Jaleada 20p', 'Jaleada 20p'), ('04Jaleada 10p', 'Jaleada 10p'), ('05Moca 20p', 'Moca 20p'), ('06Moca 10p', 'Moca 10p'), ('07Selva Negra20p', 'Selva Negra20p'), ('08Selva Negra 10p', 'Selva Negra 10p'), ('09Tres Leches 20p', 'Tres Leches 20p'), ('10Tres Leches 10p', 'Tres Leches 10p'), ('11Maracuya 20p', 'Maracuya 20p'), ('12Maracuya 10p', 'Maracuya 10p'), ('13Chocomoca 20p', 'Chocomoca 20p'), ('14Chocomoca 10p', 'Chocomoca 10p'), ('15Chocodelis 20p', 'Chocodelis 20p'), ('16Chocodelis 10p', 'Chocodelis 10p'), ('17Porcion de Frutas', 'Porcion de Frutas'), ('18Porcion Moca', 'Porcion Moca'), ('19Porcion Selva Negra', 'Porcion Selva Negra'), ('20Porcion 3 Leches', 'Porcion 3 Leches'), ('21Porcion Maracuya', 'Porcion Maracuya'), ('22Porcion chocomooka', 'Porcion chocomooka'), ('23Porcion Chocodelis', 'Porcion Chocodelis'), ('24Alfafor', 'Alfafor'), ('25Copas', 'Copas'), ('26Chesecake vaso', 'Chesecake vaso'), ('27Mouse Copa', 'Mouse Copa'), ('28Mouse entero', 'Mouse entero'), ('29Mil hojas', 'Mil hojas'), ('30Brownie Chocolate', 'Brownie Chocolate'), ('31Aspic', 'Aspic'), ('32Brownie Maracuya', 'Brownie Maracuya'), ('33Bomba', 'Bomba'), ('34Brazo Gitano', 'Brazo Gitano'), ('35Pie de manzana porc.', 'Pie de manzana porc.'), ('36Pie de limon  porc.', 'Pie de limon  porc.'), ('37Pie de piña porc.', 'Pie de piña porc.'), ('38Pie de frutas porc.', 'Pie de frutas porc.'), ('39Pie de manzana ent.', 'Pie de manzana ent.'), ('40Pie de limon ent.', 'Pie de limon ent.'), ('41Pie de piña  ent.', 'Pie de piña  ent.'), ('42Pie de frutas ent.', 'Pie de frutas ent.'), ('43Conitos', 'Conitos'), ('44Cupcakes', 'Cupcakes'), ('45Queque ', 'Queque '), ('46Muffy', 'Muffy'), ('47Mini bomba', 'Mini bomba'), ('48Rollo', 'Rollo'), ('49Empanadas', 'Empanadas'), ('50Croisant', 'Croisant'), ('51Pan Pizza', 'Pan Pizza'), ('52Blanca de 30p', 'Blanca de 30p')], default='Blanca 20p', max_length=200),
        ),
    ]
