# Generated by Django 5.2.9 on 2026-01-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(choices=[('01Blanca 20p', '01Blanca 20p'), ('02Blanca 10p', '02Blanca 10p'), ('03Jaleada 20p', '03Jaleada 20p'), ('04Jaleada 10p', '04Jaleada 10p'), ('05Moca 20p', '05Moca 20p'), ('06Moca 10p', '06Moca 10p'), ('07Selva Negra20p', '07Selva Negra20p'), ('08Selva Negra 10p', '08Selva Negra 10p'), ('09Tres Leches 20p', '09Tres Leches 20p'), ('10Tres Leches 10p', '10Tres Leches 10p'), ('11Maracuya 20p', '11Maracuya 20p'), ('12Maracuya 10p', '12Maracuya 10p'), ('13Chocomoca 20p', '13Chocomoca 20p'), ('14Chocomoca 10p', '14Chocomoca 10p'), ('15Chocodelis 20p', '15Chocodelis 20p'), ('16Chocodelis 10p', '16Chocodelis 10p'), ('17Porcion de Frutas', '17Porcion de Frutas'), ('18Porcion Moca', '18Porcion Moca'), ('19Porcion Selva Negra', '19Porcion Selva Negra'), ('20Porcion 3 Leches', '20Porcion 3 Leches'), ('21Porcion Maracuya', '21Porcion Maracuya'), ('22Porcion chocomooka', '22Porcion chocomooka'), ('23Porcion Chocodelis', '23Porcion Chocodelis'), ('24Alfafor', '24Alfafor'), ('25Copas', '25Copas'), ('26Chesecake vaso', '26Chesecake vaso'), ('27Mouse Copa', '27Mouse Copa'), ('28Mouse entero', '28Mouse entero'), ('29Mil hojas', '29Mil hojas'), ('30Brownie Chocolate', '30Brownie Chocolate'), ('31Aspic', '31Aspic'), ('32Brownie Maracuya', '32Brownie Maracuya'), ('33Bomba', '33Bomba'), ('34Brazo Gitano', '34Brazo Gitano'), ('35Pie de manzana porc.', '35Pie de manzana porc.'), ('36Pie de limon  porc.', '36Pie de limon  porc.'), ('37Pie de piña porc.', '37Pie de piña porc.'), ('38Pie de frutas porc.', '38Pie de frutas porc.'), ('39Pie de manzana ent.', '39Pie de manzana ent.'), ('40Pie de limon ent.', '40Pie de limon ent.'), ('41Pie de piña  ent.', '41Pie de piña  ent.'), ('42Pie de frutas ent.', '42Pie de frutas ent.'), ('43Conitos', '43Conitos'), ('44Cupcakes', '44Cupcakes'), ('45Queque ', '45Queque '), ('46Muffy', '46Muffy'), ('47Mini bomba', '47Mini bomba'), ('48Rollo', '48Rollo'), ('49Empanadas', '49Empanadas'), ('50Croisant', '50Croisant'), ('51Pan Pizza', '51Pan Pizza'), ('52Blanca de 30p', '52Blanca de 30p')], default='01Blanca 20p', max_length=200),
        ),
    ]
